# Generated by Django 4.0 on 2021-12-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
