# Generated by Django 4.0 on 2021-12-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlescope_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='primary',
        ),
    ]
