# Generated by Django 4.0 on 2021-12-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articlescope_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='scopes',
            new_name='tag',
        ),
    ]
